title:
  en: Procedural Animations
  es: Animaciones Procedurales
finished: finished
descriptionShort:
  en: "In this project, I employed the concept of zero keyframes: instead of using images for texture, I drew and rendered the frames of a moving creature to make it appear alive. The main idea was to create fish-like creatures with fins and wobbly eyes. I then incorporated some of my previous work on Inverse Kinematics to generate the legs. The results are incredible visuals of creatures that move as if they were alive!"
  es: "En este proyecto he usado el concepto de cero keyframes: en lugar de usar imágenes como texturas, se dibujan y renderizan los fotogramas de una criatura en movimiento para que parezca viva. La idea era crear criaturas parecidas a peces, con aletas y ojos saltones. Después incorporé parte de mi trabajo previo en Inverse Kinematics para generar las patas. El resultado son imágenes impresionantes de criaturas que se mueven como si tuvieran vida y te sigue!"
descriptionLong:
  en: |
    Using Python, Pygame, and NumPy, I employed the concept of zero keyframes: instead of using images for texture, I drew and rendered the frames of a moving creature to make it appear alive. The main idea was to create fish-like creatures with fins and wobbly eyes. I then incorporated some of my previous work on Inverse Kinematics to generate the legs. With some smoothing curve techniques, I made the shapes of the creatures smooth and visually appealing. The results are incredible visuals of creatures that move as if they were alive and following you!
  es: |
    Utilizando Python, Pygame y NumPy, he aplicado el concepto de cero keyframes: en lugar de usar imágenes como texturas, se dibujan y renderizan los fotogramas de una criatura en movimiento para que parezca viva. La idea era crear criaturas parecidas a peces, con aletas y ojos saltones, y luego añadí parte de mi trabajo en Inverse Kinematics para darles patas. Con algunas técnicas de suavizado logré que las formas se vieran más fluidas y naturales. El resultado son imágenes sorprendentes de criaturas que se mueven como si estuvieran vivas y siguen el cursor.
technologies: [python, pygame, numpy]
tags: [other]
logo: readme_images/Procedural (1).webp
screenShoots:
  - readme_images/Procedural (1).webp
  - readme_images/Procedural (10).webp
  - readme_images/Procedural (2).webp
  - readme_images/Procedural (3).webp
  - readme_images/Procedural (4).webp
  - readme_images/Procedural (5).webp
  - readme_images/Procedural (6).webp
  - readme_images/Procedural (7).webp
  - readme_images/Procedural (8).webp
  - readme_images/Procedural (9).webp
youtube: DXGSoyjN9PA
slug: Procedural_Animations
order: 68
featured: false
